NUmpy arrayas operations

In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5.6, 6, 7, 8, 9, 10])
print("basic sliccing", arr[2:4])  # Slicing from index 2 to 4 (exclusive   )

basic sliccing [3. 4.]


    2D arrays ki indexing slicicng 

In [12]:
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]])
print("2D arrays Slicing specific element",arr2D[1,2] )
print("entire rows" , arr2D[1])
print( "entire col", arr2D[:,1])

2D arrays Slicing specific element 6
entire rows [4 5 6]
entire col [2 5 8]


Sorting in arrays


In [4]:
unsorted_arr = np.array([3, 1, 4, 2, 5])
sorted_arr = np.sort(unsorted_arr)
print("sorted array", sorted_arr)  # Sorts the array in ascending order

arr_2d_Unsorted = np.array([[3, 1, 4],
                            [2, 5, 6],
                            [7, 8, 9]])
print("sorted 2d by col", np.sort(arr_2d_Unsorted, axis=0)) 
print("sorted 2d by row", np.sort(arr_2d_Unsorted, axis=1))# Sort by columns

sorted array [1 2 3 4 5]
sorted 2d by col [[2 1 4]
 [3 5 6]
 [7 8 9]]
sorted 22d by col [[1 3 4]
 [2 5 6]
 [7 8 9]]


## filtering the arrays

In [5]:
numbs = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("filtering the array", numbs[numbs > 5])  # Filtering elements
enven = numbs[numbs % 2 == 0]  # Filtering even numbers
print("filtering the array", enven)  # Filtering even numbers
print("filtering the array", numbs[numbs % 2 == 0]) #also filtering even numbers

filtering the array [ 6  7  8  9 10]
filtering the array [ 2  4  6  8 10]
filtering the array [ 2  4  6  8 10]


## Filter with mask

In [6]:
mask = numbs > 5
print("filtering with mask", numbs[mask])  # Filtering with mask

filtering with mask [ 6  7  8  9 10]


## fancy indexing and np.where()

In [9]:
indices = [0,2,4]  # List of indices to select specific elements from the array
print(" ye index se item return karta hai", numbs[indices])  # Returns elements at indices 0, 2, and 4 from 'numbs'

where_result = np.where(numbs > 6)  # Returns the indices where the condition (numbs > 6) is True
print("where NP :", numbs[where_result])  # Prints the elements of 'numbs' where the value is greater than 6

 ye index se item return karta hai [1 3 5]
where NP : [ 7  8  9 10]


In [14]:
condition_arr = np.where(numbs > 5, numbs*2, numbs) 
# If element in 'numbs' > 5, multiply by 2, else keep original value
print(condition_arr)  # Prints the resulting array after applying the condition

con = np.where(numbs> 5 , "true", "false")
print("the true false arr", con)

[ 1  2  3  4  5 12 14 16 18 20]
the true false arr ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## adding and removing data

In [ ]:
arr1 = np.array([1,2,3,4,5,6])  # Create a 1D numpy array 'arr1'
arr2 = np.array([7,8,9,10,11,12])  # Create another 1D numpy array 'arr2' of the same shape
combine_arrays = arr1 + arr2  # Element-wise addition of arr1 and arr2
print(combine_arrays)  # Print the result of element-wise addition
combine_arrys = np.concatenate((arr1, arr2))  # Concatenate arr1 and arr2 into a single array
print(combine_arrys)  # Print

[ 8 10 12 14 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


arrays compatibity

In [ ]:
a = np.array([1,2,3,4,5])   # Create a 1D numpy array 'a'
b = np.array([6,7,8,9,10])  # Create another 1D numpy array 'b' with the same shape as 'a'
c = np.array([11,12,13,14]) # Create a 1D numpy array 'c' with a different shape

print("comnpatibility shape", a.shape == b.shape)  # Check if 'a' and 'b' have the same shape (compatible for element-wise operations)
print(a.shape == c.shape)  # Check if 'a' and 'c' have the same shape

comnpatibility shape True
False


adding new rows and colums

In [28]:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])
new_row = np.array([7, 8, 9])

# Adding a new row
new_array_with_row = np.append(original_array, [new_row], axis=0)
print("new array with row", new_array_with_row)

new_row_vstack = np.vstack((original_array, new_row))
print("new array with row using vstack", new_row_vstack)



# Adding a new column
new_col = np.array([[4], [7]])
new_array_with_col = np.append(original_array, new_col, axis=1)
print("new array with col", new_array_with_col)


new_col_hstack = np.hstack((original_array, new_col))
print("new array with col using hstack", new_col_hstack)


new array with row [[1 2 3]
 [4 5 6]
 [7 8 9]]
new array with row using vstack [[1 2 3]
 [4 5 6]
 [7 8 9]]
new array with col [[1 2 3 4]
 [4 5 6 7]]
new array with col using hstack [[1 2 3 4]
 [4 5 6 7]]


delelte arrqys

In [ ]:
# Create a 2D numpy array (3x3)
arrays = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

delete_row = 1  # Index of the row to delete (second row, since indexing starts at 0)

# Delete the specified row from the array (axis=0 means row)
new_array_after_row_deletion = np.delete(arrays, delete_row,

new array after row deletion [[1 2 3]
 [7 8 9]]
