numpy array and basics

In [2]:
import numpy as np

In [2]:
arrr_1D = np.array([1,2,3,4])
print("arr 1D", arrr_1D)

arr 1D [1 2 3 4]


In [3]:
arr_2D = np.array([[1,2,3],[1,2,3]])
print("arrays 2D", arr_2D)

arrays 2D [[1 2 3]
 [1 2 3]]


list vs numpy arrays


In [5]:
##multipy both

list_py = [1,2,3,4]
print("the multipy list", list_py * 2)
arr_np = np.array([1,2,3,4]) ## elements wise multiplication
print("the multipy numpy", arr_np * 2)

the multipy list [1, 2, 3, 4, 1, 2, 3, 4]
the multipy numpy [2 4 6 8]


In [13]:
import time
start = time.time()
py_lsit = [i*2 for i in range(1000000)] # its very slow
print("the time taken for list", time.time() - start)

start_numpy = time.time()
np_array = np.array([i*2 for i in range(1000000)]) # its very slow  
# arrange havve a better performance with 
# start - stop - step   step
# step is optional and means the difference between two elements
np_arange = np.arange(1000000) * 2  # its very fast
print("the time taken for arange", time.time() - start_numpy)  
print("the time taken for numpyarr", time.time() - start_numpy)

the time taken for list 0.07591724395751953
the time taken for arange 0.11213564872741699
the time taken for numpyarr 0.11222028732299805


creating array from scrash

In [3]:
zeros = np.zeros((2,3)) # 2 rows and 3 columns
print("the zeros array", zeros)

ones = np.ones((2,3)) # 2 rows and 3 columns
print("the ones array", ones)

full = np.full((2,2), 5) # 2 rows and 3 columns with all elements as 5
print("the full array", full)

identity = np.identity(3) # 3x3 identity matrix
print("the identity matrix", identity)

eye = np.eye(3) # 3x3 identity matrix
print("the eye matrix", eye)

random = np.random.rand(2,3) # 2 rows and 3 columns with random values
print("the random array", random)

random_int = np.random.randint(1, 10, (2,3)) # 2 rows and 3 columns with random integers between 1 and 10
print("the random int array", random_int)

squence = np.arange(1, 10, 2) # start - stop - step
print("the sequence array", squence)

linspace = np.linspace(1, 10, 6) # start - stop - number of elements
print("the linspace array", linspace)


the zeros array [[0. 0. 0.]
 [0. 0. 0.]]
the ones array [[1. 1. 1.]
 [1. 1. 1.]]
the full array [[5 5]
 [5 5]]
the identity matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
the eye matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
the random array [[0.5018497  0.25232399 0.62655161]
 [0.23764313 0.14713839 0.78857082]]
the random int array [[9 9 6]
 [9 2 8]]
the sequence array [1 3 5 7 9]
the linspace array [ 1.   2.8  4.6  6.4  8.2 10. ]


Vector Matrix and Tensor


In [23]:
vector = np.array([1,2,3,4,5]) # 1D vector
print("the vector", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]]) # 2D matrix
print("the matrix", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6], [7,8]]]) # 3D tensor
print("the tensor", tensor)

the vector [1 2 3 4 5]
the matrix [[1 2 3]
 [4 5 6]]
the tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


arrays properties

In [31]:
arr = np.array([[1,2,3,4], [5,6,7,8]]) # 2D array
print("the array", arr)
print("shape", arr.shape)
print("size", arr.size)
print("dtype", arr.dtype)
print("Dimension", arr.ndim) # number of dimensions
print("itemsize", arr.itemsize) # size of each element in bytes
print("nbytes", arr.nbytes) # total size of the array in bytes
print("T", arr.T) # transpose of the array
print("flatten", arr.flatten()) # flatten the array
print("reshape", arr.reshape(2,4)) # reshape the array to 2x2
print("max", arr.max()) # maximum value in the array
print("min", arr.min()) # minimum value in the array
print("sum", arr.sum()) # sum of the elements in the array
print("mean", arr.mean()) # mean of the elements in the array
print("std", arr.std()) # standard deviation of the elements in the array
print("var", arr.var()) # variance of the elements in the array
print("argmax", arr.argmax()) # index of the maximum value in the array
print("argmin", arr.argmin()) # index of the minimum value in the array
print("sort", np.sort(arr)) # sort the array
print("unique", np.unique(arr)) # unique elements in the array
print("where", np.where(arr > 5)) # indices of the elements greater than 5
print("all", np.all(arr > 0)) # check if all elements are greater than 0
print("any", np.any(arr > 5)) # check if any element is greater than 5
print("clip", arr.clip(3, 6)) # clip the values between 3 and 6
print("argsort", arr.argsort()) # indices that would sort the array
print("diagonal", np.diagonal(arr)) # diagonal elements of the array
print("trace", np.trace(arr)) # trace of the array
print("dot product", np.dot(arr, arr.T)) # dot product of the array with its transpose
#print("cross product", np.cross(vector, vector)) # cross product of the vector with itself
print("outer product", np.outer(vector, vector)) # outer product of the vector with itself
print("inner product", np.inner(vector, vector)) # inner product of the vector with itself
print("einsum", np.einsum('ij->ji', arr)) # einsum notation for array manipulation  
print("broadcasting", arr + 10) # broadcasting the array with a scalar

the array [[1 2 3 4]
 [5 6 7 8]]
shape (2, 4)
size 8
dtype int64
Dimension 2
itemsize 8
nbytes 64
T [[1 5]
 [2 6]
 [3 7]
 [4 8]]
flatten [1 2 3 4 5 6 7 8]
reshape [[1 2 3 4]
 [5 6 7 8]]
max 8
min 1
sum 36
mean 4.5
std 2.29128784747792
var 5.25
argmax 7
argmin 0
sort [[1 2 3 4]
 [5 6 7 8]]
unique [1 2 3 4 5 6 7 8]
where (array([1, 1, 1]), array([1, 2, 3]))
all True
any True
clip [[3 3 3 4]
 [5 6 6 6]]
argsort [[0 1 2 3]
 [0 1 2 3]]
diagonal [1 6]
trace 7
dot product [[ 30  70]
 [ 70 174]]
outer product [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
inner product 55
einsum [[1 5]
 [2 6]
 [3 7]
 [4 8]]
broadcasting [[11 12 13 14]
 [15 16 17 18]]


In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]]) # 2D array
print("the array", arr)
